name: shooting_companion
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Tento řádek přidává balíček http
  cookie_jar: ^4.0.8
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.1 # nebo nejnovější verzi
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8 # Cupertino Icons font for iOS style icons.
  vibration: ^2.0.1
  flutter_native_splash: ^2.4.3
  geolocator: ^13.0.2
  flutter_secure_storage: ^9.2.2
  flutter_bcrypt: ^1.0.8
  local_auth: ^2.3.0
  internet_connection_checker_plus: ^2.5.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  android_intent_plus: ^5.2.0
  share_plus: ^10.1.2
  device_info_plus: ^11.1.1
  intl: ^0.19.0
  cross_file: ^0.3.4+2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^5.0.0 # Recommended lints to encourage good coding practices.

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets to be used in the application, including icons and images.
  assets:
    - assets/icon/app_icon.png # Path to the app icon.
    - assets/splash_large.png

flutter_native_splash:
  image: assets/splash_large.png
  color: "#D3D3D3"
  android_gravity: fill # změna z center na fill
  fullscreen: true
  android_12:
    image: assets/splash_large.png
    icon_background_color: "#D3D3D3"
  web: false
